In [115]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

In [116]:
%matplotlib notebook

In [120]:
def odefunc(u, t, params):
    
    Nx,Ny = np.shape(u); #print(Nx,Ny)
    dux = np.zeros((Nx, Ny))
    duy = np.zeros((Nx, Ny))
    du = np.zeros((Nx, Ny))
    
    Fx = params[0]
    Fy = params[0]
    
   # Compute u at inner mesh points
    for i in range(1, Nx-1):
        for j in range(1, Ny-1):
                dux[0, j]=(u[Nx-1, j] - 2*u[0, j] + u[1, j])*Fx
                dux[i, j] = (u[i-1, j] - 2*u[i, j] + u[i+1, j])*Fx
                dux[Nx-1, j]=(u[Nx-2, j] - 2*u[Nx-1, j] + u[0, j])*Fx
            
                duy[i, 0]=(u[i, Ny-1] - 2*u[i, 0] + u[i, 1])*Fy
                duy[i, j] = (u[i, j-1] - 2*u[i, j] + u[i, j+1])*Fy
                duy[i, Ny-1]=(u[i, Ny-2] - 2*u[i, Ny-1] + u[i, 0])*Fy
                
                du = dux + duy
            
    #for i in range(0, Nx):
     #   for j in range(0, Ny):
      #          u[i, j] = u[i,j] + du[i,j]


    return du

In [123]:
L = 1
T = 10
dT = 2

# Nx = 500
# Ny = 500

Nx = 5
Ny = 5
x = np.linspace(0, L, Nx) # mesh points in space
y = np.linspace(0, L, Ny) 
dx = x[1] - x[0]
dy = y[1] - y[0]
t = np.arange(0, T, dT) # mesh points in time
a = 0.0000001

Fx = a/dx**2
Fy = a/dy**2
 
# Initialize u
u   = np.zeros((Nx, Ny))

# Check up on the sizes
print(np.shape(u))

# Add initial bump at midx,midy spike and integrate up to T
midx = int(Nx/2); 
midy = int(Ny/2); 
u[midx,midy] = 1

print(np.shape(u))
print(u)

# Bundle parameters for ODE solver
params = [Fx,Fy]; print (params)



(5, 5)
(5, 5)
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[1.5999999999999999e-06, 1.5999999999999999e-06]


In [124]:
du = odefunc(u, t, params)
print (du)

print(np.shape(du))

[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.60000000e-06   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   1.60000000e-06  -6.40000000e-06   1.60000000e-06
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.60000000e-06   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]]
(5, 5)


In [106]:
#sol = odeint(odefunc, u, t, args = (params,))