In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

In [2]:
%matplotlib notebook

In [15]:
L = 1
T = 10000
dT = 2

# Nx = 500
# Ny = 500

Nx = 5
Ny = 5

a = 0.0000001

In [52]:
x = np.linspace(0, L, Nx) # mesh points in space
y = np.linspace(0, L, Ny) 
dx = x[1] - x[0]
dy = y[1] - y[0]
t = np.arange(0, T, dT)    # mesh points in time
Nt = len(t)
Fx = a*dT/dx**2
Fy = a*dT/dy**2
u   = np.zeros((Nx, Ny)) # unknown u at new time level
u_1 = np.zeros((Nx, Ny))
dux = np.zeros(Nx)
duy = np.zeros(Ny)
du = np.zeros((Nx, Ny))
du = np.zeros((Nx, Ny))

# Check up on the sizes
print(np.shape(u))

# Initialize u
midx = int(Nx/2)
midy = int(Ny/2)
u[midx,midy] = 1

# Bundle parameters for ODE solver
params = [Fx,Fy]; print (params)


# u_1[250, 100] = 1
# u_1[150, 250] = 0.5
# u_1[450, 300] = 1.5

(5, 5)
[3.2e-06, 3.2e-06]


In [55]:
def odefunc(u, t, params):
    
    Nx,Ny = np.shape(u); #print(Nx,Ny)
    dux = np.zeros((Nx, Ny))
    duy = np.zeros((Nx, Ny))
    du = np.zeros((Nx, Ny))
    
    Fx = params[0]
    Fy = params[0]

    # Compute u at inner mesh points
    for i in range(1, Nx-1):
        for j in range(1, Ny-1):
                dux[i, j] = Fx*(u[i-1, j] - 2*u[i, j] + u[i+1, j]) 
                #dux[0, j]=Fx*(u[Nx, j] - 2*u[0, j] + u[1, j]) 
                #dux[Nx, j]=Fx*(u[Nx-1, j] - 2*u[Nx, j] + u[0, j]) 
            
                duy[i, j] = Fy*(u[i, j-1] - 2*u[i, j] + u[i, j+1])
                #duy[i, 0]=Fy*(u[i, Ny] - 2*u[i, 0] + u[i, 1])
                #duy[i, Ny]=Fy*(u[i, Ny-1] - 2*u[i, Ny] + u[i, 0])
                
                du = dux + duy
            
#         for i in range(0, Nx+1):
#             for j in range(0, Ny+1):
#                 u[i, j] = u[i,j] + du[i,j]


    return du

In [56]:
du = odefunc(u, t, params)
print (du)

[[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  3.20e-06  0.00e+00  0.00e+00]
 [ 0.00e+00  3.20e-06 -1.28e-05  3.20e-06  0.00e+00]
 [ 0.00e+00  0.00e+00  3.20e-06  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]]


In [7]:
#sol = odeint(odefunc,u_1,Nt)